version: '3.7'

services:
  mtproxy:
    image: telegrammessenger/proxy:latest
    restart: always
    hostname: mtproxy
    container_name: mtproxy
    environment:
      - SECRET=${SECRET}
      - TAG=${TAG}
    volumes:
      - ${FOLDER}:/data
    ports:
      - ${PORT}:443
    network_mode: "host"
