version: '3.7'

services:
  mtproxy:
    image: telegrammessenger/proxy:latest
    restart: always
    hostname: mtproxy
    container_name: mtproxy
    environment:
      - SECRET=${SECRET}
    volumes:
      - /srv/services/proxy-config:/data
    ports:
      - 1945:443
    networks:
      - mtproxy-net

networks:
  mtproxy-net:
    name: mtproxy-net
